import { PartyPlan } from '../types';

export const SAMPLE_PARTIES: PartyPlan[] = [
  {
    id: 'preset_bbq',
    title: 'CymbalMart Backyard BBQ & Smokeout',
    eventType: 'BBQ Cookout',
    theme: 'Rustic Summer Grill & Lawn Games',
    guestCount: { adults: 18, kids: 6, total: 24 },
    durationHours: 4.5,
    budget: { targetBudget: 350, currency: '$', estimatedTotal: 315 },
    storeLocation: 'CymbalMart Supercenter #104 (Austin North)',
    dietaryRestrictions: ['2 Vegetarians', '1 Gluten-Free guest'],
    venueType: 'Backyard & Deck',
    equipment: ['Charcoal Grill', 'Smoker / Slow Cooker', '2 Large Coolers', 'Outdoor Speakers'],
    vibeAndNotes: 'Relaxed sunshine vibe, smokey aromas, chilled drinks in galvanized tubs, fun cornhole matches.',
    playlistVibe: 'Classic 70s rock, upbeat funk & modern folk acoustic',
    schedule: [
      { time: '2:00 PM', phase: 'Arrival & Welcome Drinks', description: 'Guests grab cold drinks from coolers, watermelon slices and chips & queso out.' },
      { time: '3:15 PM', phase: 'Grill Smoke & First Searing', description: 'Hot sausages, brisket sliders, smash burgers and charred corn served hot.' },
      { time: '4:30 PM', phase: 'Lawn Games & Cornhole Tournament', description: 'Tournament bracket kickoff, cold beer & sparkling mocktails circulating.' },
      { time: '5:45 PM', phase: 'Dessert & Smores Station', description: 'Skillet peach crisp with vanilla ice cream and fire pit s\'mores.' },
      { time: '6:30 PM', phase: 'Golden Hour Wind-down', description: 'String lights illuminate yard, leftover packaging boxes provided.' },
    ],
    menu: {
      appetizers: [
        {
          id: 'p1_app1',
          name: 'Smoky Queso Dip with Warm Pretzel Bites & Tortillas',
          description: 'Melted monterey jack, smoked gouda, roasted poblanos, and scallions in a cast iron skillet.',
          servings: 24,
          dietaryTags: ['Vegetarian'],
          prepDifficulty: 'Easy',
          prepAheadTime: 'Can mix cheese day before',
          ingredients: [
            { name: 'Cymbal Choice Smoked Gouda & Jack Cheese', quantity: 2, unit: 'lbs', category: 'Dairy & Deli', estimatedCost: 14.0 },
            { name: 'Cymbal Essentials Green Chiles & Diced Tomatoes', quantity: 2, unit: 'cans', category: 'Pantry & Dry Goods', estimatedCost: 4.5 },
            { name: 'Cymbal Organic Tortilla Chips & Pretzels', quantity: 3, unit: 'bags', category: 'Pantry & Dry Goods', estimatedCost: 12.0 },
          ],
          quickInstructions: ['Melt cheeses slowly with green chiles in skillet or slow cooker.', 'Keep warm on lowest setting.', 'Serve with chips and pretzel bites.'],
        },
        {
          id: 'p1_app2',
          name: 'Sweet Chili Lime Watermelon Skewers with Mint',
          description: 'Chilled juicy watermelon cubes dusted with Tajín spice and fresh spearmint leaves.',
          servings: 24,
          dietaryTags: ['Vegan', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          prepAheadTime: 'Morning of event',
          ingredients: [
            { name: 'Cymbal Fresh Seedless Watermelon', quantity: 1, unit: 'large melon', category: 'Produce', estimatedCost: 7.0 },
            { name: 'Fresh Organic Mint & Limes', quantity: 1, unit: 'pack', category: 'Produce', estimatedCost: 3.5 },
          ],
        },
      ],
      mains: [
        {
          id: 'p1_main1',
          name: 'Slow-Smoked Pulled Pork Carnitas & Sliders',
          description: 'Tender seasoned pork shoulder pulled with tangy Carolina gold and sweet hickory sauces.',
          servings: 20,
          dietaryTags: ['Gluten-Free (without bun)'],
          prepDifficulty: 'Medium',
          prepAheadTime: 'Cook day before / morning in slow cooker',
          ingredients: [
            { name: 'Cymbal Butcher Choice Pork Shoulder (Boston Butt)', quantity: 10, unit: 'lbs', category: 'Meat & Seafood', estimatedCost: 38.0 },
            { name: 'Cymbal Bakery Brioche Slider Buns', quantity: 24, unit: 'buns', category: 'Bakery & Bread', estimatedCost: 11.0 },
            { name: 'Cymbal Pitmaster BBQ Sauce Duo', quantity: 2, unit: 'bottles', category: 'Pantry & Dry Goods', estimatedCost: 7.5 },
          ],
        },
        {
          id: 'p1_main2',
          name: 'Marinated Honey-Mustard Chicken Skewers',
          description: 'Grilled chicken breast skewers with bell peppers and red onion wedges.',
          servings: 18,
          dietaryTags: ['Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Chicken Breast Fillets', quantity: 6, unit: 'lbs', category: 'Meat & Seafood', estimatedCost: 22.0 },
            { name: 'Organic Bell Peppers & Red Onions', quantity: 6, unit: 'items', category: 'Produce', estimatedCost: 6.5 },
          ],
        },
        {
          id: 'p1_main3',
          name: 'Grilled Halloumi & Veggie Skewers (Veg Option)',
          description: 'Thick grilled halloumi cheese with zucchini, cherry tomatoes, and herb chimichurri.',
          servings: 6,
          dietaryTags: ['Vegetarian', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Choice Halloumi Cheese Blocks', quantity: 2, unit: 'packs', category: 'Dairy & Deli', estimatedCost: 11.0 },
            { name: 'Organic Zucchini & Cherry Tomatoes', quantity: 2, unit: 'pints', category: 'Produce', estimatedCost: 5.5 },
          ],
        },
      ],
      sides: [
        {
          id: 'p1_side1',
          name: 'Southern Apple Cider Vinegar Slaw',
          description: 'Crisp green & purple cabbage, shredded carrots, and honey-cider dressing (no mayo to sit well in heat).',
          servings: 24,
          dietaryTags: ['Vegan', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Shredded Coleslaw Mix', quantity: 3, unit: 'bags', category: 'Produce', estimatedCost: 6.5 },
            { name: 'Cymbal Organic Apple Cider Vinegar & Olive Oil', quantity: 1, unit: 'bottle', category: 'Pantry & Dry Goods', estimatedCost: 4.0 },
          ],
        },
        {
          id: 'p1_side2',
          name: 'Charred Sweet Corn on the Cob with Herb Butter',
          description: 'Grilled in foil with smoked paprika, garlic, and fresh chives.',
          servings: 24,
          dietaryTags: ['Vegetarian', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Sweet Corn Ears', quantity: 20, unit: 'ears', category: 'Produce', estimatedCost: 15.0 },
            { name: 'Cymbal Essentials Salted Butter & Fresh Chives', quantity: 2, unit: 'sticks', category: 'Dairy & Deli', estimatedCost: 4.0 },
          ],
        },
      ],
      desserts: [
        {
          id: 'p1_des1',
          name: 'Cast-Iron Peach & Blackberry Skillet Crisp',
          description: 'Bubbling cinnamon peaches and blackberries with golden oat crumble topping and vanilla ice cream.',
          servings: 24,
          dietaryTags: ['Vegetarian'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Fresh Sliced Peaches & Blackberries', quantity: 4, unit: 'lbs', category: 'Produce', estimatedCost: 12.0 },
            { name: 'Cymbal Essentials Rolled Oats & Brown Sugar', quantity: 1, unit: 'kit', category: 'Pantry & Dry Goods', estimatedCost: 6.0 },
            { name: 'Cymbal Creamery Vanilla Bean Ice Cream', quantity: 2, unit: 'tubs', category: 'Dairy & Deli', estimatedCost: 9.0 },
          ],
        },
      ],
      drinks: [
        {
          id: 'p1_drk1',
          name: 'Bourbon Sweet Tea & Peach Punch (Self-Serve Dispenser)',
          type: 'Cocktail',
          description: 'Southern black sweet tea infused with peach puree, lemon juice, mint sprigs, and bourbon.',
          batchServings: 30,
          alcoholic: true,
          ingredients: [
            { name: 'Kentucky Bourbon / Whiskey', quantity: 1, unit: '750ml bottle', estimatedCost: 26.0 },
            { name: 'Cymbal Essentials Iced Tea & Peach Nectar', quantity: 4, unit: 'liters', estimatedCost: 8.0 },
            { name: 'Fresh Lemons & Mint', quantity: 6, unit: 'lemons', estimatedCost: 4.0 },
          ],
          batchingInstructions: 'In a 2-gallon drink dispenser, combine iced tea, peach nectar, and bourbon with lemon wheels and ice.',
        },
        {
          id: 'p1_drk2',
          name: 'Sparkling Cucumber Lime Cooler (Mocktail / Kids)',
          type: 'Mocktail',
          description: 'Crisp cucumber ribbons, fresh lime juice, agave nectar, and sparkling soda.',
          batchServings: 25,
          alcoholic: false,
          ingredients: [
            { name: 'Organic Cucumbers & Limes', quantity: 4, unit: 'cucumbers', estimatedCost: 5.0 },
            { name: 'Cymbal Sparkling Seltzer Water', quantity: 12, unit: 'cans', estimatedCost: 7.0 },
          ],
        },
      ],
    },
    shoppingList: [
      { id: 'bbq_1', name: 'Cymbal Butcher Pork Shoulder (Boston Butt)', category: 'Meat & Seafood', quantityNeeded: 10, unit: 'lbs', packSizeSuggestion: '2 x 5 lb roast packs', estimatedPrice: 38.0, suggestedStore: 'CymbalMart Supercenter', department: 'Meat & Seafood', aisle: 'Aisle 12 - Butcher Counter', brandTier: 'Cymbal Choice', checked: false },
      { id: 'bbq_2', name: 'Cymbal Fresh Chicken Breast Cutlets', category: 'Meat & Seafood', quantityNeeded: 6, unit: 'lbs', packSizeSuggestion: 'Bulk family pack', estimatedPrice: 22.0, suggestedStore: 'CymbalMart Supercenter', department: 'Meat & Seafood', aisle: 'Aisle 12 - Butcher Counter', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_3', name: 'Cymbal Choice Halloumi Cheese Blocks', category: 'Dairy & Deli', quantityNeeded: 2, unit: 'packs', estimatedPrice: 11.0, suggestedStore: 'CymbalMart Supercenter', department: 'Dairy & Deli', aisle: 'Aisle 2 - Specialty Cheese', brandTier: 'Cymbal Choice', dietaryTag: 'Vegetarian', checked: false },
      { id: 'bbq_4', name: 'Cymbal Bakery Brioche Slider Buns', category: 'Bakery & Bread', quantityNeeded: 24, unit: 'buns', packSizeSuggestion: '2 packs of 12 rolls', estimatedPrice: 11.0, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Fresh Bakery', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_5', name: 'Cymbal Fresh Sweet Yellow Corn', category: 'Produce', quantityNeeded: 20, unit: 'ears', packSizeSuggestion: 'Bulk crate or loose ears', estimatedPrice: 15.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Produce Island', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_6', name: 'Cymbal Fresh Seedless Watermelon', category: 'Produce', quantityNeeded: 1, unit: 'melon', estimatedPrice: 7.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Produce Island', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_7', name: 'Cymbal Fresh Coleslaw Mix', category: 'Produce', quantityNeeded: 3, unit: 'bags', estimatedPrice: 6.5, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Salad Wall', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_8', name: 'Organic Peaches & Fresh Blackberries', category: 'Produce', quantityNeeded: 4, unit: 'lbs', estimatedPrice: 12.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Organic Berry Wall', brandTier: 'Cymbal Organic', checked: false },
      { id: 'bbq_9', name: 'Kentucky Bourbon (750ml)', category: 'Alcohol', quantityNeeded: 1, unit: 'bottle', estimatedPrice: 26.0, suggestedStore: 'CymbalMart Spirits Depot', department: 'Alcohol', aisle: 'Aisle 10 - Spirits', brandTier: 'National Brand', checked: false },
      { id: 'bbq_10', name: 'Craft Summer Ciders & Pale Ale (24-pack)', category: 'Alcohol', quantityNeeded: 1, unit: '24-pack case', estimatedPrice: 32.0, suggestedStore: 'CymbalMart Supercenter', department: 'Alcohol', aisle: 'Aisle 10 - Craft Beer Walk-in', brandTier: 'National Brand', checked: false },
      { id: 'bbq_11', name: 'Cymbal Sparkling Seltzers Variety (24-pk)', category: 'Beverages & Mixers', quantityNeeded: 24, unit: 'cans', estimatedPrice: 14.0, suggestedStore: 'CymbalMart Supercenter', department: 'Beverages & Mixers', aisle: 'Aisle 8 - Beverages', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_12', name: 'CymbalMart Party Ice Bags (10 lb)', category: 'Ice', quantityNeeded: 3, unit: 'bags (30 lbs)', packSizeSuggestion: '3 x 10 lb bags', estimatedPrice: 9.75, suggestedStore: 'CymbalMart Supercenter', department: 'Ice', aisle: 'Front Entrance Freezer', brandTier: 'Cymbal Essentials', notes: '2 bags for drink coolers, 1 bag for cocktail punch', checked: false },
      { id: 'bbq_13', name: 'Cymbal Heavy-Duty Compostable Plates (50 ct)', category: 'Tableware & Disposables', quantityNeeded: 50, unit: 'plates', estimatedPrice: 14.99, suggestedStore: 'CymbalMart Supercenter', department: 'Tableware & Disposables', aisle: 'Aisle 14 - Party & Paper', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_14', name: 'Cymbal Clear Acrylic Party Cups & Napkins', category: 'Tableware & Disposables', quantityNeeded: 100, unit: 'pack', estimatedPrice: 11.5, suggestedStore: 'CymbalMart Supercenter', department: 'Tableware & Disposables', aisle: 'Aisle 14 - Party & Paper', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'bbq_15', name: 'Outdoor Citronella Candles & String Lights', category: 'Decorations & Balloons', quantityNeeded: 1, unit: 'set', estimatedPrice: 16.0, suggestedStore: 'CymbalMart Supercenter', department: 'Decorations & Balloons', aisle: 'Aisle 15 - Seasonal Patio', brandTier: 'Cymbal Choice', checked: false },
    ],
    budgetBreakdown: {
      food: 165,
      drinks: 87,
      tablewareAndSupplies: 36,
      decorations: 16,
      buffer: 11,
    },
    prepTimeline: [
      { timeframe: '3 Days Before', tasks: ['Check propane tank or buy charcoal at CymbalMart.', 'Borrow or clean 2 large drink coolers.', 'Send headcount confirmation reminder.'] },
      { timeframe: '1 Day Before', tasks: ['Schedule CymbalMart Curbside Pickup or Delivery for groceries.', 'Dry rub pork shoulder and start slow smoke or slow cooker.', 'Make vinegar coleslaw (improves overnight).', 'Slice watermelon and store in airtight containers.', 'Brew iced tea concentrate.'] },
      { timeframe: 'Morning of Event', tasks: ['Pick up 3 bags of ice from CymbalMart front freezer.', 'Load drink coolers with beer, seltzers, and water.', 'Set out lawn games and speaker.'] },
      { timeframe: '30 Mins Before', tasks: ['Mix bourbon sweet tea in dispenser.', 'Fire up grill for skewers and corn.', 'Put out queso skillet on warm.'] },
    ],
    hostTips: [
      'Pre-shred the pork an hour before guests arrive and keep it moist in a slow cooker with apple cider and BBQ juices.',
      'Place ice in the drink coolers at least 1 hour before party time with cold water so cans chill rapidly.',
      'Have permanent markers near the cup dispenser so guests write their names and reuse cups!',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset_taco',
    title: 'CymbalMart Street Taco & Margarita Fiesta',
    eventType: 'Taco Bar Fiesta',
    theme: 'Authentic Street Tacos, Guacamole Bar & Citrus Margaritas',
    guestCount: { adults: 14, kids: 4, total: 18 },
    durationHours: 4,
    budget: { targetBudget: 240, currency: '$', estimatedTotal: 218 },
    storeLocation: 'CymbalMart Supercenter #104 (Austin North)',
    dietaryRestrictions: ['Vegetarian option', 'Gluten-Free corn tortillas'],
    venueType: 'Patio & Kitchen Island',
    equipment: ['Slow Cooker', 'Cast Iron Skillet', 'Citrus Juicer', 'Taco Holders'],
    vibeAndNotes: 'Vibrant Latin beats, warm pressed tortillas, colorful salsa bowls, and fresh-squeezed citrus.',
    playlistVibe: 'Cumbia, upbeat Latin funk, Spanish acoustic guitar & modern pop',
    schedule: [
      { time: '5:00 PM', phase: 'Chips, Salsas & Welcome Margaritas', description: 'Fresh chips, trio of salsas, guacamole bar, and ice cold margaritas.' },
      { time: '6:00 PM', phase: 'Taco Bar Grand Opening', description: 'Braised carnitas, seasoned chicken tinga, grilled rajas & black beans.' },
      { time: '7:30 PM', phase: 'Mexican Street Corn & Music', description: 'Warm elote cups with cotija and tajín, lively conversation.' },
      { time: '8:30 PM', phase: 'Churros & Spiced Hot Chocolate', description: 'Crisp cinnamon churros with dulce de leche dip.' },
    ],
    menu: {
      appetizers: [
        {
          id: 't_app1',
          name: 'Cymbal Guacamole & Trio of Roasted Salsas',
          description: 'Hand-mashed Hass avocados with lime, cilantro, pico de gallo, salsa verde, and habanero crema.',
          servings: 18,
          dietaryTags: ['Vegan', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Hass Avocados', quantity: 8, unit: 'avocados', category: 'Produce', estimatedCost: 9.5 },
            { name: 'Cymbal Organic Tortilla Chips', quantity: 3, unit: 'bags', category: 'Pantry & Dry Goods', estimatedCost: 10.5 },
            { name: 'Cymbal Choice Roasted Salsa Trio', quantity: 3, unit: 'jars', category: 'Pantry & Dry Goods', estimatedCost: 8.0 },
          ],
        },
      ],
      mains: [
        {
          id: 't_main1',
          name: 'Slow-Cooked Citrus Carnitas & Chicken Tinga',
          description: 'Crispy pork carnitas and shredded chicken simmered with chipotle, fire-roasted tomatoes, and Mexican oregano.',
          servings: 18,
          dietaryTags: ['Gluten-Free'],
          prepDifficulty: 'Medium',
          ingredients: [
            { name: 'Cymbal Butcher Boneless Pork & Chicken Breast', quantity: 7, unit: 'lbs', category: 'Meat & Seafood', estimatedCost: 28.0 },
            { name: 'Cymbal Essentials Yellow Corn & Flour Tortillas', quantity: 48, unit: 'tortillas', category: 'Bakery & Bread', estimatedCost: 7.5 },
            { name: 'Cymbal Choice Cotija & Monterey Jack Cheese', quantity: 2, unit: 'packs', category: 'Dairy & Deli', estimatedCost: 7.0 },
          ],
        },
        {
          id: 't_main2',
          name: 'Grilled Poblano Rajas & Seasoned Black Beans',
          description: 'Charred poblano peppers with sweet corn, caramelized onions, and cumin black beans for vegetarian tacos.',
          servings: 6,
          dietaryTags: ['Vegetarian', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Fresh Poblano Peppers & Limes', quantity: 6, unit: 'items', category: 'Produce', estimatedCost: 4.5 },
            { name: 'Cymbal Organic Black Beans', quantity: 3, unit: 'cans', category: 'Pantry & Dry Goods', estimatedCost: 3.5 },
          ],
        },
      ],
      sides: [
        {
          id: 't_side1',
          name: 'Warm Elote Cups with Crema, Cotija & Tajín',
          description: 'Off-the-cob sweet corn tossed with lime mayonnaise, Mexican crema, crumbled cotija, and chili seasoning.',
          servings: 18,
          dietaryTags: ['Vegetarian', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Sweet Corn', quantity: 12, unit: 'ears', category: 'Produce', estimatedCost: 9.0 },
            { name: 'Mexican Crema & Tajín Seasoning', quantity: 1, unit: 'kit', category: 'Dairy & Deli', estimatedCost: 4.5 },
          ],
        },
      ],
      desserts: [
        {
          id: 't_des1',
          name: 'Bakery Churro Bites with Warm Dulce de Leche',
          description: 'Golden cinnamon churro pastries served with warm caramel dulce de leche sauce.',
          servings: 18,
          dietaryTags: ['Vegetarian'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Bakery Churro Bites Platter', quantity: 2, unit: 'boxes', category: 'Bakery & Bread', estimatedCost: 10.0 },
            { name: 'Cymbal Essentials Dulce de Leche', quantity: 1, unit: 'jar', category: 'Pantry & Dry Goods', estimatedCost: 3.5 },
          ],
        },
      ],
      drinks: [
        {
          id: 't_drk1',
          name: 'Fresh Agave Lime Margarita Pitchers',
          type: 'Cocktail',
          description: '100% Blue Agave Blanco Tequila, freshly squeezed lime juice, triple sec, and organic agave nectar.',
          batchServings: 24,
          alcoholic: true,
          ingredients: [
            { name: '100% Blue Agave Tequila (750ml)', quantity: 1, unit: 'bottle', estimatedCost: 24.0 },
            { name: 'Cymbal Fresh Limes (2 lb bag)', quantity: 2, unit: 'bags', estimatedCost: 6.0 },
            { name: 'Cymbal Organic Agave Nectar', quantity: 1, unit: 'bottle', estimatedCost: 4.5 },
          ],
        },
        {
          id: 't_drk2',
          name: 'Cymbal Hibiscus Agua Fresca & Jarritos',
          type: 'Mocktail',
          description: 'Chilled iced hibiscus agua fresca and assorted Mexican sodas for kids and designated drivers.',
          batchServings: 16,
          alcoholic: false,
          ingredients: [
            { name: 'Dried Hibiscus Flowers & Cane Sugar', quantity: 1, unit: 'pack', estimatedCost: 4.0 },
            { name: 'Jarritos Mexican Sodas (12-pack)', quantity: 1, unit: 'pack', estimatedCost: 11.0 },
          ],
        },
      ],
    },
    shoppingList: [
      { id: 'tac_1', name: 'Cymbal Butcher Pork & Chicken Meat', category: 'Meat & Seafood', quantityNeeded: 7, unit: 'lbs', estimatedPrice: 28.0, suggestedStore: 'CymbalMart Supercenter', department: 'Meat & Seafood', aisle: 'Aisle 12 - Butcher Counter', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_2', name: '100% Blue Agave Tequila Blanco (750ml)', category: 'Alcohol', quantityNeeded: 1, unit: 'bottle', estimatedPrice: 24.0, suggestedStore: 'CymbalMart Spirits Depot', department: 'Alcohol', aisle: 'Aisle 10 - Spirits', brandTier: 'National Brand', checked: false },
      { id: 'tac_3', name: 'Cymbal Fresh Hass Avocados (8 ct)', category: 'Produce', quantityNeeded: 8, unit: 'avocados', estimatedPrice: 9.5, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Produce Island', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_4', name: 'Cymbal Organic Tortilla Chips (3 bags)', category: 'Pantry & Dry Goods', quantityNeeded: 3, unit: 'bags', estimatedPrice: 10.5, suggestedStore: 'CymbalMart Supercenter', department: 'Pantry & Dry Goods', aisle: 'Aisle 6 - Snacks & Chips', brandTier: 'Cymbal Organic', checked: false },
      { id: 'tac_5', name: 'Cymbal Fresh Sweet Corn (12 ears)', category: 'Produce', quantityNeeded: 12, unit: 'ears', estimatedPrice: 9.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Fresh Produce', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_6', name: 'Cymbal Yellow Corn & Flour Tortillas', category: 'Bakery & Bread', quantityNeeded: 48, unit: 'tortillas', estimatedPrice: 7.5, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Bakery', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_7', name: 'Cymbal Choice Cotija & Jack Cheeses', category: 'Dairy & Deli', quantityNeeded: 2, unit: 'packs', estimatedPrice: 7.0, suggestedStore: 'CymbalMart Supercenter', department: 'Dairy & Deli', aisle: 'Aisle 2 - Dairy', brandTier: 'Cymbal Choice', checked: false },
      { id: 'tac_8', name: 'Cymbal Fresh Limes & Cilantro Bunches', category: 'Produce', quantityNeeded: 2, unit: 'bags', estimatedPrice: 6.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Citrus Wall', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_9', name: 'Cymbal Bakery Churro Bites & Dulce de Leche', category: 'Bakery & Bread', quantityNeeded: 2, unit: 'boxes', estimatedPrice: 13.5, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Bakery', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_10', name: 'Jarritos Mexican Sodas Variety 12-Pack', category: 'Beverages & Mixers', quantityNeeded: 1, unit: 'case', estimatedPrice: 11.0, suggestedStore: 'CymbalMart Supercenter', department: 'Beverages & Mixers', aisle: 'Aisle 8 - Beverages', brandTier: 'National Brand', checked: false },
      { id: 'tac_11', name: 'CymbalMart Premium Ice Bags (20 lbs)', category: 'Ice', quantityNeeded: 2, unit: 'bags', estimatedPrice: 6.5, suggestedStore: 'CymbalMart Supercenter', department: 'Ice', aisle: 'Front Entrance Freezer', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'tac_12', name: 'Fiesta Papel Picado Banner & Colorful Plates', category: 'Tableware & Disposables', quantityNeeded: 1, unit: 'kit', estimatedPrice: 18.0, suggestedStore: 'CymbalMart Supercenter', department: 'Tableware & Disposables', aisle: 'Aisle 14 - Party Supplies', brandTier: 'Cymbal Choice', checked: false },
    ],
    budgetBreakdown: {
      food: 115,
      drinks: 55,
      tablewareAndSupplies: 28,
      decorations: 12,
      buffer: 8,
    },
    prepTimeline: [
      { timeframe: '1 Day Before', tasks: ['Simmer carnitas in slow cooker with citrus and cumin.', 'Brew hibiscus tea concentrate for agua fresca.', 'Juice limes for margarita base.'] },
      { timeframe: '2 Hours Before', tasks: ['Grill poblano rajas in skillet.', 'Slice avocados and mix guacamole.', 'Set out warming pans for tortillas.'] },
      { timeframe: '30 Mins Before', tasks: ['Pour margaritas into pitchers with salt rims.', 'Warm taco meats on low.', 'Queue upbeat Latin playlist.'] },
    ],
    hostTips: [
      'Keep tortillas soft by wrapping batches of 12 in damp kitchen towels inside a low oven or tortilla warmer.',
      'Salt only half the margarita glass rims so guests who prefer unsalted can drink comfortably.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset_cocktail',
    title: 'CymbalMart Tapas & Artisan Wine Soirée',
    eventType: 'Cocktail Party',
    theme: 'Modern Spanish Tapas & Craft Wine Tasting',
    guestCount: { adults: 16, kids: 0, total: 16 },
    durationHours: 3.5,
    budget: { targetBudget: 320, currency: '$', estimatedTotal: 298 },
    storeLocation: 'CymbalMart Supercenter #104 (Austin North)',
    dietaryRestrictions: ['Nut-free focus', '2 Pescatarians'],
    venueType: 'Living Room & Dining Island',
    equipment: ['Cocktail Shaker & Jiggers', 'Oven / Air Fryer', 'Wooden Charcuterie Boards', 'Wine Glasses'],
    vibeAndNotes: 'Sophisticated yet cozy, moody ambient lighting, acoustic bossa nova, warm bite-sized tapas passing continuously.',
    playlistVibe: 'French lounge, bossa nova, chic jazz & neo-soul beats',
    schedule: [
      { time: '6:30 PM', phase: 'Doors Open & Welcome Spritz', description: 'Elderflower Cava spritz handed to guests, sprawling charcuterie & cheese grazing board open.' },
      { time: '7:15 PM', phase: 'Warm Tapas Wave 1', description: 'Garlic gambas al ajillo, blistered shishito peppers, and pan con tomate.' },
      { time: '8:00 PM', phase: 'Warm Tapas Wave 2 & Red Wine', description: 'Spanish tortilla española wedges and chorizo stuffed dates.' },
      { time: '9:00 PM', phase: 'Dark Chocolate & Espresso Bites', description: 'Churro bites with warm dark chocolate ganache dip.' },
      { time: '10:00 PM', phase: 'Nightcap', description: 'Herbal digestifs and conversation.' },
    ],
    menu: {
      appetizers: [
        {
          id: 'p2_app1',
          name: 'Grand Tapas Charcuterie & Artisan Cheese Board',
          description: 'Manchego, Iberico jamon, prosciutto, marinated olives, fig jam, marcona-style roasted seeds, artisan crackers.',
          servings: 16,
          dietaryTags: ['Nut-Free'],
          prepDifficulty: 'Easy',
          prepAheadTime: 'Assemble 1 hour before',
          ingredients: [
            { name: 'Cymbal Choice Aged Manchego & Goat Cheese', quantity: 1.5, unit: 'lbs', category: 'Dairy & Deli', estimatedCost: 18.0 },
            { name: 'Cymbal Deli Cured Prosciutto & Jamon Serrano', quantity: 1, unit: 'lb', category: 'Dairy & Deli', estimatedCost: 16.0 },
            { name: 'Cymbal Organic Olives & Fig Jam', quantity: 2, unit: 'jars', category: 'Pantry & Dry Goods', estimatedCost: 9.0 },
            { name: 'Artisan Flatbreads & Crackers', quantity: 3, unit: 'boxes', category: 'Bakery & Bread', estimatedCost: 11.0 },
          ],
        },
        {
          id: 'p2_app2',
          name: 'Pan con Tomate with Flaky Sea Salt & Olive Oil',
          description: 'Toasted rustic sourdough rubbed with fresh garlic, grated vine tomatoes, and extra virgin olive oil.',
          servings: 16,
          dietaryTags: ['Vegan'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Bakery Sourdough Boule', quantity: 2, unit: 'loaves', category: 'Bakery & Bread', estimatedCost: 9.0 },
            { name: 'Cymbal Fresh Beefsteak Tomatoes & Garlic', quantity: 4, unit: 'tomatoes', category: 'Produce', estimatedCost: 4.5 },
          ],
        },
      ],
      mains: [
        {
          id: 'p2_main1',
          name: 'Sizzling Garlic Shrimp (Gambas al Ajillo)',
          description: 'Plump shrimp sautéed in fragrant olive oil, sliced garlic, chili flakes, and fresh parsley.',
          servings: 16,
          dietaryTags: ['Gluten-Free', 'Pescatarian'],
          prepDifficulty: 'Medium',
          ingredients: [
            { name: 'Cymbal Seafood Wild Jumbo Peeled Shrimp', quantity: 3, unit: 'lbs', category: 'Meat & Seafood', estimatedCost: 27.0 },
            { name: 'Garlic Bulbs & Fresh Italian Parsley', quantity: 3, unit: 'heads', category: 'Produce', estimatedCost: 4.0 },
          ],
        },
        {
          id: 'p2_main2',
          name: 'Traditional Potato & Onion Tortilla Española',
          description: 'Golden, custard-like Spanish omelet served in tender bite-sized pinchos with garlic aioli.',
          servings: 16,
          dietaryTags: ['Vegetarian', 'Gluten-Free'],
          prepDifficulty: 'Medium',
          ingredients: [
            { name: 'Cymbal Fresh Yukon Gold Potatoes', quantity: 3, unit: 'lbs', category: 'Produce', estimatedCost: 4.5 },
            { name: 'Cymbal Organic Farm Fresh Eggs (Dozen)', quantity: 2, unit: 'cartons', category: 'Dairy & Deli', estimatedCost: 8.0 },
          ],
        },
      ],
      sides: [
        {
          id: 'p2_side1',
          name: 'Blistered Shishito Peppers with Smoked Sea Salt',
          description: 'Quick-seared sweet green peppers drizzled with lemon juice and flaky Maldon salt.',
          servings: 16,
          dietaryTags: ['Vegan', 'Gluten-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Fresh Shishito Peppers', quantity: 1.5, unit: 'lbs', category: 'Produce', estimatedCost: 8.0 },
          ],
        },
      ],
      desserts: [
        {
          id: 'p2_des1',
          name: 'Mini Cinnamon Sugar Churro Bites & Dark Chocolate Dip',
          description: 'Crispy warm churro bites served with 70% dark chocolate espresso dipping ganache.',
          servings: 16,
          dietaryTags: ['Vegetarian'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Bakery Churro Bites', quantity: 2, unit: 'boxes', category: 'Bakery & Bread', estimatedCost: 9.0 },
            { name: 'Cymbal Choice 70% Dark Chocolate & Heavy Cream', quantity: 1, unit: 'pack', category: 'Dairy & Deli', estimatedCost: 6.0 },
          ],
        },
      ],
      drinks: [
        {
          id: 'p2_drk1',
          name: 'Elderflower Cava & Rosemary Spritz',
          type: 'Cocktail',
          description: 'Spanish Brut Cava, St. Germain elderflower liqueur, sparkling water, and torched rosemary sprig.',
          batchServings: 24,
          alcoholic: true,
          ingredients: [
            { name: 'Spanish Cava Brut (Sparkling)', quantity: 3, unit: 'bottles', estimatedCost: 36.0 },
            { name: 'Elderflower Liqueur (St. Germain)', quantity: 1, unit: 'bottle', estimatedCost: 29.0 },
            { name: 'Cymbal Club Soda & Fresh Rosemary', quantity: 1, unit: 'pack', estimatedCost: 5.0 },
          ],
        },
        {
          id: 'p2_drk2',
          name: 'Spanish Rioja Tempranillo & Garnacha Red Wine',
          type: 'Beer & Wine',
          description: 'Smooth, fruit-forward Spanish red wine perfect for cured meats and shrimp.',
          batchServings: 16,
          alcoholic: true,
          ingredients: [
            { name: 'Spanish Rioja Bottles', quantity: 3, unit: 'bottles', estimatedCost: 42.0 },
          ],
        },
      ],
    },
    shoppingList: [
      { id: 'ck_1', name: 'Cymbal Seafood Jumbo Peeled Shrimp (3 lbs)', category: 'Meat & Seafood', quantityNeeded: 3, unit: 'lbs', estimatedPrice: 27.0, suggestedStore: 'CymbalMart Supercenter', department: 'Meat & Seafood', aisle: 'Aisle 12 - Seafood Counter', brandTier: 'Cymbal Choice', checked: false },
      { id: 'ck_2', name: 'Spanish Cava Brut Sparkling Wine (3 bottles)', category: 'Alcohol', quantityNeeded: 3, unit: 'bottles', estimatedPrice: 36.0, suggestedStore: 'CymbalMart Spirits Depot', department: 'Alcohol', aisle: 'Aisle 10 - Wine Cellar', brandTier: 'National Brand', checked: false },
      { id: 'ck_3', name: 'Spanish Rioja Red Wine (3 bottles)', category: 'Alcohol', quantityNeeded: 3, unit: 'bottles', estimatedPrice: 42.0, suggestedStore: 'CymbalMart Spirits Depot', department: 'Alcohol', aisle: 'Aisle 10 - Wine Cellar', brandTier: 'National Brand', checked: false },
      { id: 'ck_4', name: 'St. Germain Elderflower Liqueur', category: 'Alcohol', quantityNeeded: 1, unit: 'bottle', estimatedPrice: 29.0, suggestedStore: 'CymbalMart Spirits Depot', department: 'Alcohol', aisle: 'Aisle 10 - Spirits', brandTier: 'National Brand', checked: false },
      { id: 'ck_5', name: 'Cymbal Choice Aged Manchego & Goat Cheese', category: 'Dairy & Deli', quantityNeeded: 1.5, unit: 'lbs', estimatedPrice: 18.0, suggestedStore: 'CymbalMart Supercenter', department: 'Dairy & Deli', aisle: 'Aisle 2 - Artisan Deli', brandTier: 'Cymbal Choice', checked: false },
      { id: 'ck_6', name: 'Cymbal Deli Jamon Serrano / Prosciutto', category: 'Dairy & Deli', quantityNeeded: 1, unit: 'lb', estimatedPrice: 16.0, suggestedStore: 'CymbalMart Supercenter', department: 'Dairy & Deli', aisle: 'Aisle 2 - Artisan Deli', brandTier: 'Cymbal Choice', checked: false },
      { id: 'ck_7', name: 'Cymbal Bakery Sourdough Loaves & Crackers', category: 'Bakery & Bread', quantityNeeded: 2, unit: 'items', estimatedPrice: 12.0, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Bakery', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'ck_8', name: 'Fresh Shishito Peppers & Garlic/Parsley', category: 'Produce', quantityNeeded: 2, unit: 'bags', estimatedPrice: 12.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Produce Wall', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'ck_9', name: 'Cymbal Organic Yukon Potatoes & Eggs', category: 'Produce', quantityNeeded: 1, unit: 'pack', estimatedPrice: 12.5, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Produce Wall', brandTier: 'Cymbal Organic', checked: false },
      { id: 'ck_10', name: 'CymbalMart Cocktail Ice (Large Format)', category: 'Ice', quantityNeeded: 2, unit: 'bags', estimatedPrice: 8.0, suggestedStore: 'CymbalMart Supercenter', department: 'Ice', aisle: 'Front Entrance Freezer', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'ck_11', name: 'Cocktail Napkins, Toothpicks & Small Plates', category: 'Tableware & Disposables', quantityNeeded: 1, unit: 'kit', estimatedPrice: 14.0, suggestedStore: 'CymbalMart Supercenter', department: 'Tableware & Disposables', aisle: 'Aisle 14 - Party Supplies', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'ck_12', name: 'Taper Candles & Modern Glass Bud Vases', category: 'Decorations & Balloons', quantityNeeded: 1, unit: 'set', estimatedPrice: 16.0, suggestedStore: 'CymbalMart Supercenter', department: 'Decorations & Balloons', aisle: 'Aisle 15 - Home Accent', brandTier: 'Cymbal Choice', checked: false },
    ],
    budgetBreakdown: {
      food: 122,
      drinks: 112,
      tablewareAndSupplies: 24,
      decorations: 20,
      buffer: 20,
    },
    prepTimeline: [
      { timeframe: '1 Day Before', tasks: ['Make Tortilla Española (flavors deepen when chilled overnight, serve room temp).', 'Grate tomato pulp for pan con tomate and season with olive oil.', 'Chill Cava and white wine in refrigerator.'] },
      { timeframe: '2 Hours Before', tasks: ['Assemble charcuterie board with cheeses, jams, and crackers, cover with damp paper towel.', 'Slice sourdough bread and set by toaster or broiler.'] },
      { timeframe: '30 Mins Before', tasks: ['Prep garlic shrimp in skillet ready to cook at arrival.', 'Blister shishito peppers in hot skillet.', 'Light candles and start jazz playlist.'] },
    ],
    hostTips: [
      'Cook garlic shrimp in front of guests—the aroma fills the room and feels like a boutique tapas restaurant!',
      'Chill your cocktail glasses 30 minutes before serving for that crisp professional bar feel.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset_kids',
    title: 'CymbalMart Galactic Superhero Kids Birthday',
    eventType: 'Birthday Party',
    theme: 'Outer Space & Galactic Superheroes',
    guestCount: { adults: 8, kids: 14, total: 22 },
    durationHours: 3,
    budget: { targetBudget: 260, currency: '$', estimatedTotal: 235 },
    storeLocation: 'CymbalMart Supercenter #104 (Austin North)',
    dietaryRestrictions: ['Nut-free school protocol (Strict)', '2 Dairy-Free kids'],
    venueType: 'Home / Living Room & Backyard',
    equipment: ['Oven / Air Fryer', 'Cupcake Tier Stand', 'Party Cooler'],
    vibeAndNotes: 'High-energy, imaginative, colorful cosmic decor, fun finger foods that kids gobble up with zero fuss.',
    playlistVibe: 'Exciting superhero movie theme songs, fun Disney soundtracks & kids pop dance tracks',
    schedule: [
      { time: '1:00 PM', phase: 'Cosmic Cape Station & Tattoo Bar', description: 'Kids get superhero masks and glowing wristbands.' },
      { time: '1:30 PM', phase: 'Superhero Training Obstacle Course', description: 'Fun active games in yard/living room, laser dodge & balloon pop.' },
      { time: '2:15 PM', phase: 'Superpower Fuel Lunch Service', description: 'Cheesy pizza roll sliders, chicken tenders, fruit rocket skewers.' },
      { time: '3:00 PM', phase: 'Birthday Cake & Cosmic Cupcakes', description: 'Candle blowing ceremony, singing, and galaxy ice cream cups.' },
      { time: '3:45 PM', phase: 'Goodie Bag Mission Completion', description: 'Kids receive superhero badge goodie bags.' },
    ],
    menu: {
      appetizers: [
        {
          id: 'p3_app1',
          name: 'Fruit Rocket Skewers (Strawberries, Grapes & Melons)',
          description: 'Fun fruit skewers shaped like rockets with strawberry cone tops and pineapple booster flames.',
          servings: 22,
          dietaryTags: ['Vegan', 'Gluten-Free', 'Nut-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Strawberries, Grapes & Pineapple', quantity: 3, unit: 'packs', category: 'Produce', estimatedCost: 11.0 },
            { name: 'Safe Wooden Skewers', quantity: 1, unit: 'pack', category: 'Tableware & Disposables', estimatedCost: 3.0 },
          ],
        },
      ],
      mains: [
        {
          id: 'p3_main1',
          name: 'Pull-Apart Cheesy Pizza Roll Sliders',
          description: 'Hawaiian sweet rolls stuffed with marinara, pepperoni, mozzarella, and garlic parmesan butter glaze.',
          servings: 22,
          dietaryTags: ['Nut-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Bakery Sweet Rolls', quantity: 2, unit: '12-packs', category: 'Bakery & Bread', estimatedCost: 9.0 },
            { name: 'Cymbal Essentials Mozzarella Shreds & Pepperoni', quantity: 2, unit: 'packs', category: 'Dairy & Deli', estimatedCost: 8.5 },
            { name: 'Cymbal Organic Marinara Dipping Sauce', quantity: 2, unit: 'jars', category: 'Pantry & Dry Goods', estimatedCost: 5.0 },
          ],
        },
        {
          id: 'p3_main2',
          name: 'Crispy Baked Golden Chicken Nuggets & Tenders',
          description: 'All-natural golden chicken tenders with honey mustard, BBQ, and ranch dipping sauces.',
          servings: 20,
          dietaryTags: ['Nut-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Essentials All-Natural Chicken Tenders (4 lb)', quantity: 4, unit: 'lbs', category: 'Meat & Seafood', estimatedCost: 18.0 },
            { name: 'Cymbal Dipping Sauce Trio (Ranch, BBQ, Honey Mustard)', quantity: 3, unit: 'bottles', category: 'Pantry & Dry Goods', estimatedCost: 7.5 },
          ],
        },
      ],
      sides: [
        {
          id: 'p3_side1',
          name: 'Cosmic Veggie Cups with Creamy Dip',
          description: 'Individual clear cups with celery, baby carrots, and bell pepper sticks sitting in ranch dip.',
          servings: 22,
          dietaryTags: ['Vegetarian', 'Gluten-Free', 'Nut-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Fresh Baby Carrots, Celery & Peppers', quantity: 3, unit: 'bags', category: 'Produce', estimatedCost: 7.5 },
          ],
        },
      ],
      desserts: [
        {
          id: 'p3_des1',
          name: 'Galaxy Swirl Cupcakes with Star Sprinkles',
          description: 'Vanilla and chocolate cupcakes topped with purple-blue swirl frosting and edible glitter stars.',
          servings: 24,
          dietaryTags: ['Nut-Free'],
          prepDifficulty: 'Easy',
          ingredients: [
            { name: 'Cymbal Bakery Cosmic Cupcake Platter (24 ct)', quantity: 24, unit: 'cupcakes', category: 'Bakery & Bread', estimatedCost: 21.0 },
          ],
        },
      ],
      drinks: [
        {
          id: 'p3_drk1',
          name: 'Green Kryptonite Punch with Rainbow Sherbet',
          type: 'Punch',
          description: 'Lime sparkling beverage poured over scoops of rainbow sherbet for a bubbling magical potion.',
          batchServings: 25,
          alcoholic: false,
          ingredients: [
            { name: 'Cymbal Lemon-Lime Soda (2L)', quantity: 3, unit: 'bottles', estimatedCost: 6.0 },
            { name: 'Cymbal Creamery Rainbow Sherbet Tub', quantity: 1, unit: 'tub', estimatedCost: 4.5 },
          ],
        },
        {
          id: 'p3_drk2',
          name: 'Cold Brew Coffee & Seltzers for Grown-Ups',
          type: 'Soft Drink',
          description: 'Chilled ready-to-drink coffee cans and sparkling seltzers to keep parents energized.',
          batchServings: 12,
          alcoholic: false,
          ingredients: [
            { name: 'Cymbal Cold Brew Cans & Seltzers 12-pack', quantity: 1, unit: 'pack', estimatedCost: 14.0 },
          ],
        },
      ],
    },
    shoppingList: [
      { id: 'k_1', name: 'Cymbal Essentials Chicken Tenders (4 lb bulk)', category: 'Meat & Seafood', quantityNeeded: 4, unit: 'lbs', estimatedPrice: 18.0, suggestedStore: 'CymbalMart Supercenter', department: 'Meat & Seafood', aisle: 'Aisle 11 - Frozen Foods', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_2', name: 'Cymbal Bakery Sweet Rolls (2 packs of 12)', category: 'Bakery & Bread', quantityNeeded: 2, unit: 'packs', estimatedPrice: 9.0, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Bakery', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_3', name: 'Cymbal Bakery Cosmic Cupcake Platter (24 ct)', category: 'Bakery & Bread', quantityNeeded: 24, unit: 'cupcakes', estimatedPrice: 21.0, suggestedStore: 'CymbalMart Supercenter', department: 'Bakery & Bread', aisle: 'Aisle 3 - Bakery Case', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_4', name: 'Cymbal Mozzarella Shreds & Pepperoni', category: 'Dairy & Deli', quantityNeeded: 2, unit: 'packs', estimatedPrice: 8.5, suggestedStore: 'CymbalMart Supercenter', department: 'Dairy & Deli', aisle: 'Aisle 2 - Dairy', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_5', name: 'Cymbal Fresh Strawberries & Pineapple', category: 'Produce', quantityNeeded: 3, unit: 'items', estimatedPrice: 11.0, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Fruit Island', brandTier: 'Cymbal Fresh' as any, checked: false },
      { id: 'k_6', name: 'Cymbal Fresh Baby Carrots & Celery Hearts', category: 'Produce', quantityNeeded: 2, unit: 'bags', estimatedPrice: 7.5, suggestedStore: 'CymbalMart Supercenter', department: 'Produce', aisle: 'Aisle 1 - Fresh Veggies', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_7', name: 'Cymbal Lemon-Lime Soda & Rainbow Sherbet', category: 'Beverages & Mixers', quantityNeeded: 3, unit: 'bottles + tub', estimatedPrice: 10.5, suggestedStore: 'CymbalMart Supercenter', department: 'Beverages & Mixers', aisle: 'Aisle 8 - Beverages', brandTier: 'Cymbal Essentials', checked: false },
      { id: 'k_8', name: 'Cold Brew & Flavored Seltzers for Parents', category: 'Beverages & Mixers', quantityNeeded: 12, unit: 'cans', estimatedPrice: 14.0, suggestedStore: 'CymbalMart Supercenter', department: 'Beverages & Mixers', aisle: 'Aisle 8 - Coffee & Tea', brandTier: 'National Brand', checked: false },
      { id: 'k_9', name: 'Superhero Tablecloths, Plates & Cups Kit', category: 'Tableware & Disposables', quantityNeeded: 1, unit: 'party kit', estimatedPrice: 18.0, suggestedStore: 'CymbalMart Supercenter', department: 'Tableware & Disposables', aisle: 'Aisle 14 - Party Supplies', brandTier: 'Cymbal Choice', checked: false },
      { id: 'k_10', name: 'Cosmic Balloon Garland & Foil Superheroes', category: 'Decorations & Balloons', quantityNeeded: 1, unit: 'decor set', estimatedPrice: 22.0, suggestedStore: 'CymbalMart Supercenter', department: 'Decorations & Balloons', aisle: 'Aisle 14 - Balloons & Decor', brandTier: 'Cymbal Choice', checked: false },
      { id: 'k_11', name: 'Goodie Bag Favors (Tattoos, Glow Bracelets)', category: 'Miscellaneous', quantityNeeded: 15, unit: 'bags', estimatedPrice: 16.0, suggestedStore: 'CymbalMart Supercenter', department: 'Miscellaneous', aisle: 'Aisle 14 - Party Favors', brandTier: 'Cymbal Choice', checked: false },
    ],
    budgetBreakdown: {
      food: 92,
      drinks: 28,
      tablewareAndSupplies: 24,
      decorations: 42,
      buffer: 15,
    },
    prepTimeline: [
      { timeframe: '2 Days Before', tasks: ['Inflate balloon garland and assemble goodie favor bags.', 'Confirm superhero costume or outfit.'] },
      { timeframe: '1 Day Before', tasks: ['Schedule CymbalMart Delivery for party snacks.', 'Thread fruit skewers and store in airtight tray.'] },
      { timeframe: 'Morning of Party', tasks: ['Bake chicken nuggets and pizza roll sliders (keep warm in 170F oven).', 'Prep veggie cups with ranch.', 'Put out coloring sheets and tattoo station.'] },
    ],
    hostTips: [
      'Pre-portion ice cream cups the night before and store in muffin tins in the freezer so cake serving takes 30 seconds!',
      'Keep extra juice boxes and wet wipes right near the main craft table for instant cleanup.',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
